package main

import (
	"github.com/BurntSushi/toml"
	"log"
)

type AutoGenerated struct {
	Select string `toml:"Select"`
	Qiniu  struct {
		AccessKey string `toml:"AccessKey"`
		SecretKey string `toml:"SecretKey"`
		Bucket    string `toml:"bucket"`
	} `toml:"Qiniu"`
	Hdfs struct {
		Namenode string `toml:"namenode"`
		RootPath string `toml:"rootPath"`
	} `toml:"Hdfs"`
	Local struct {
		RootPath string `toml:"rootPath"`
	} `toml:"Local"`
}
func GetConfig() AutoGenerated {
	var favorites AutoGenerated
	if _, err := toml.DecodeFile("conf.toml", &favorites); err != nil {
		log.Fatal(err)
	}
	return favorites;
}
